seed_everything: 1234
ckpt_path: null # to resume

trainer:
  fast_dev_run: false
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true 
  devices: [0]
  accumulate_grad_batches: 8
  num_nodes: 1
  precision: 16
  max_epochs: 100
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 10
  log_every_n_steps: 5

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "./output/finetune.GTZANGenre.MERT-v1-95M/checkpoints/" # Please specify your own path
        filename: "best"
        save_top_k: 1 # -1 to save all checkpoints
    - class_path: marble.modules.callbacks.LoadLatestCheckpointCallback # for testing
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: "val/acc"               # 要监控的 metric 名称
        patience: 20                       # 在多少次验证后无改进就停止
        mode: "max"                       # “val_loss” 下降时才算改进
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "marble"
      name: "finetune.GTZANGenre.MERT-v1-95M"
      save_dir: "./output/finetune.GTZANGenre.MERT-v1-95M/"


model:
  class_path: marble.tasks.GTZANGenre.finetune.FinetuneAudioTask
  init_args:
    sample_rate: 24000
    use_ema: false

    encoder:
      class_path: marble.encoders.MERT.model.MERT_v1_95M_Encoder
      init_args:
        pre_trained_folder: null
        train_mode: lora  # also supports lora, or full
        lora_r: 8
        lora_alpha: 8
        lora_dropout: 0.0
        lora_target_modules: ["q_proj", "v_proj"]
        force_half: false
        preprocess_in_forward: false
      
    emb_transforms:
      - class_path: marble.modules.transforms.LayerSelector
        init_args:
          layers: [7]  # something like [1, 3, "10..72"]
      - class_path: marble.modules.transforms.TimeAvgPool # (batch_size, num_layers, 1, hidden_size)
    
    decoders:
      - class_path: marble.modules.decoders.MLPDecoder
        init_args:
          in_dim: 768
          out_dim: 10 # 10 genres
          hidden_layers: [512]
          activation_fn: 
            class_path: torch.nn.ReLU
          dropout: 0.2

    losses:
      - class_path: torch.nn.CrossEntropyLoss
        init_args:
          reduction: mean

    metrics:
      train:
        acc:
          class_path: torchmetrics.Accuracy
          init_args:
            num_classes: 10
            task: multiclass
      val:
        acc:
          class_path: torchmetrics.Accuracy
          init_args:
            num_classes: 10
            task: multiclass
      test:
        acc:
          class_path: torchmetrics.Accuracy
          init_args:
            num_classes: 10
            task: multiclass
    
data:
  class_path: marble.tasks.GTZANGenre.datamodule.GTZANGenreDataModule
  init_args:
    batch_size: 8
    num_workers: 8

    audio_transforms:
      train:
        - class_path: marble.encoders.MERT.model.MERT_v1_95M_FeatureExtractor
          init_args:
            pre_trained_folder: null
            squeeze: true
      val:
        - class_path: marble.encoders.MERT.model.MERT_v1_95M_FeatureExtractor
          init_args:
            pre_trained_folder: null
            squeeze: true
      test:
        - class_path: marble.encoders.MERT.model.MERT_v1_95M_FeatureExtractor
          init_args:
            pre_trained_folder: null
            squeeze: true

    train:
      class_path: marble.tasks.GTZANGenre.datamodule.GTZANGenreAudioTrain
      init_args:
        sample_rate: 24000
        channels: 1
        clip_seconds: 30.2
        min_clip_ratio: 0.8 # at least 80% of the clip length
        channel_mode: first # first, random, mix
        jsonl: data/GTZAN/GTZANGenre.train.jsonl
    val:
      class_path: marble.tasks.GTZANGenre.datamodule.GTZANGenreAudioVal
      init_args:
        sample_rate: 24000
        channels: 1
        clip_seconds: 30.2
        min_clip_ratio: 0.8
        channel_mode: first
        jsonl: data/GTZAN/GTZANGenre.val.jsonl
    test:
      class_path: marble.tasks.GTZANGenre.datamodule.GTZANGenreAudioTest
      init_args:
        sample_rate: 24000
        channels: 1
        clip_seconds: 30.2
        min_clip_ratio: 0.8
        channel_mode: first
        jsonl: data/GTZAN/GTZANGenre.test.jsonl

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 5e-3

lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    mode: "max"
    factor: 0.5
    patience: 6
    monitor: "val/acc"
