ckpt_path: null # to resume

trainer:
  fast_dev_run: false
  accelerator: gpu
  # strategy: ddp # or ddp_find_unused_parameters
  devices: [0]
  accumulate_grad_batches: 8
  num_nodes: 1
  precision: bf16 # or 32, or 16
  max_epochs: 50
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 10
  log_every_n_steps: 50

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "./output/probe.Chords1217.MynaBase/checkpoints/" # Please specify your own path
        filename: "best"
        save_top_k: 1 # -1 to save all checkpoints
    - class_path: marble.modules.callbacks.LoadLatestCheckpointCallback # for testing
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: "val/acc"               # 要监控的 metric 名称
        patience: 10                       # 在多少次验证后无改进就停止
        mode: "max"                       # “val_loss” 下降时才算改进
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "marble"
      name: "probe.Chords1217.MynaBase"
      save_dir: "./output/probe.Chords1217.MynaBase/"

model:
  class_path: marble.tasks.Chords1217.probe.ProbeAudioTask
  init_args:
    sample_rate: 16000
    use_ema: false

    encoder:
      class_path: marble.encoders.Myna.model.MynaEncoder
      init_args:
        model_name: oriyonay/myna-base
        train_mode: freeze  # also supports full

    emb_transforms:
      - class_path: marble.modules.transforms.TimeInterpolation
        init_args:
          target_frames: 375
          mode: nearest

    decoders:
      - class_path: marble.modules.decoders.MLPDecoderKeepTime
        init_args:
          in_dim: 384
          out_dim: 25
          hidden_layers: [512]
          activation_fn:
            class_path: torch.nn.ReLU
          dropout: 0.2

    losses:
      - class_path: marble.tasks.Chords1217.probe.ChordCrossEntropyLoss
        init_args:
          time_dim_mismatch_tol: 5

    metrics:
      train:
        acc:
          class_path: marble.tasks.Chords1217.probe.ChordAccuracy
          init_args:
            time_dim_mismatch_tol: 5
            ignore_index: -1 # ignore the non maj min chords

      val:
        acc:
          class_path: marble.tasks.Chords1217.probe.ChordAccuracy
          init_args:
            time_dim_mismatch_tol: 5
            ignore_index: -1 # ignore the non maj min chords

      test:
        acc:
          class_path: marble.tasks.Chords1217.probe.ChordAccuracy
          init_args:
            time_dim_mismatch_tol: 5
            ignore_index: -1 # ignore the non maj min chords

data:
  class_path: marble.tasks.Chords1217.datamodule.Chords1217DataModule
  init_args:
    batch_size: 8
    num_workers: 16

    audio_transforms:
      train:
        - class_path: marble.modules.transforms.MelSpectrogram
          init_args:
            sample_rate: 16000
            n_fft: 1024
            win_length: 1024
            hop_length: 256
            n_mels: 128
        - class_path: marble.modules.transforms.PadToMultiple
          init_args:
            multiple: 16
      val:
        - class_path: marble.modules.transforms.MelSpectrogram
          init_args:
            sample_rate: 16000
            n_fft: 1024
            win_length: 1024
            hop_length: 256
            n_mels: 128
        - class_path: marble.modules.transforms.PadToMultiple
          init_args:
            multiple: 16
      test:
        - class_path: marble.modules.transforms.MelSpectrogram
          init_args:
            sample_rate: 16000
            n_fft: 1024
            win_length: 1024
            hop_length: 256
            n_mels: 128
        - class_path: marble.modules.transforms.PadToMultiple
          init_args:
            multiple: 16

    train:
      class_path: marble.tasks.Chords1217.datamodule.Chords1217AudioTrain
      init_args:
        sample_rate: 16000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.1 # at least 10% of the clip length
        channel_mode: random # first, random, mix
        jsonl: data/Chords1217/Chords1217.train.jsonl
        label_freq: 25
        backend: "soundfile" # speed up random read flac
    val:
      class_path: marble.tasks.Chords1217.datamodule.Chords1217AudioVal
      init_args:
        sample_rate: 16000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.1
        channel_mode: mix
        jsonl: data/Chords1217/Chords1217.val.jsonl
        label_freq: 25
        backend: "soundfile" # speed up random read flac
    test:
      class_path: marble.tasks.Chords1217.datamodule.Chords1217AudioTest
      init_args:
        sample_rate: 16000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.1
        channel_mode: mix
        jsonl: data/Chords1217/Chords1217.test.jsonl
        label_freq: 25
        backend: "soundfile" # speed up random read flac

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-3

lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    mode: "max"
    factor: 0.5
    patience: 5
    monitor: "val/acc"
