seed_everything: 1234
ckpt_path: null # to resume

trainer:
  fast_dev_run: false
  accelerator: gpu
  # strategy: ddp # or ddp_find_unused_parameters
  devices: [0]
  accumulate_grad_batches: 4
  num_nodes: 1
  precision: bf16 # or 32, or 16
  max_epochs: 50
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 10
  log_every_n_steps: 50

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "./output/probe.HookTheoryStructure.MynaVertical/checkpoints/" # Please specify your own path
        filename: "best"
        save_top_k: 1 # -1 to save all checkpoints
    - class_path: marble.modules.callbacks.LoadLatestCheckpointCallback # for testing
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: "val/acc"               # 要监控的 metric 名称
        patience: 10                       # 在多少次验证后无改进就停止
        mode: "max"                       # “val_loss” 下降时才算改进
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "marble"
      name: "probe.HookTheoryStructure.MynaVertical"
      save_dir: "./output/probe.HookTheoryStructure.MynaVertical/"

model:
  class_path: marble.tasks.HookTheoryStructure.probe.ProbeAudioTask
  init_args:
    sample_rate: 16000
    use_ema: false

    encoder:
      class_path: marble.encoders.Myna.model.MynaEncoder
      init_args:
        model_name: oriyonay/myna-vertical
        train_mode: freeze  # also supports full

    emb_transforms:
      - class_path: marble.modules.transforms.TimeAvgPool # (batch_size, num_layers, 1, hidden_size)

    decoders:
      - class_path: marble.modules.decoders.MLPDecoder
        init_args:
          in_dim: 384
          out_dim: 7 # 7 structure classes
          hidden_layers: [512]
          activation_fn:
            class_path: torch.nn.ReLU
          dropout: 0.2

    losses:
      - class_path: torch.nn.CrossEntropyLoss
        init_args:
          reduction: mean

    metrics:
      train:
        acc:
          class_path: torchmetrics.Accuracy
          init_args:
            num_classes: 7
            task: multiclass
      val:
        acc:
          class_path: torchmetrics.Accuracy
          init_args:
            num_classes: 7
            task: multiclass
      test:
        acc:
          class_path: torchmetrics.Accuracy
          init_args:
            num_classes: 7
            task: multiclass

data:
  class_path: marble.tasks.HookTheoryStructure.datamodule.HookTheoryStructureDataModule
  init_args:
    batch_size: 16
    num_workers: 16

    audio_transforms:
      train:
        - class_path: marble.modules.transforms.MelSpectrogram
          init_args:
            sample_rate: 16000
            n_fft: 1024
            win_length: 1024
            hop_length: 256
            n_mels: 128
        - class_path: marble.modules.transforms.PadToMultiple
          init_args:
            multiple: 16
      val:
        - class_path: marble.modules.transforms.MelSpectrogram
          init_args:
            sample_rate: 16000
            n_fft: 1024
            win_length: 1024
            hop_length: 256
            n_mels: 128
        - class_path: marble.modules.transforms.PadToMultiple
          init_args:
            multiple: 16
      test:
        - class_path: marble.modules.transforms.MelSpectrogram
          init_args:
            sample_rate: 16000
            n_fft: 1024
            win_length: 1024
            hop_length: 256
            n_mels: 128
        - class_path: marble.modules.transforms.PadToMultiple
          init_args:
            multiple: 16

    train:
      class_path: marble.tasks.HookTheoryStructure.datamodule.HookTheoryStructureAudioTrain
      init_args:
        sample_rate: 16000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.1 # at least 10% of the clip length
        channel_mode: random # first, random, mix
        jsonl: data/HookTheory/HookTheoryStructure.train.jsonl
    val:
      class_path: marble.tasks.HookTheoryStructure.datamodule.HookTheoryStructureAudioVal
      init_args:
        sample_rate: 16000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.1
        channel_mode: mix
        jsonl: data/HookTheory/HookTheoryStructure.val.jsonl
    test:
      class_path: marble.tasks.HookTheoryStructure.datamodule.HookTheoryStructureAudioTest
      init_args:
        sample_rate: 16000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.1
        channel_mode: mix
        jsonl: data/HookTheory/HookTheoryStructure.test.jsonl

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-3

lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    mode: "max"
    factor: 0.1
    patience: 5
    monitor: "val/acc"
